HPC <- read.csv("household_power_consumption.txt",sep=";")
HPC$Date <- as.Date(HPC$Date,"%d/%m/%Y")
part1 <- subset(HPC,HPC$Date=="2007-02-01")
part2 <- subset(HPC,HPC$Date=="2007-02-02")
edata <- rbind(part1,part2)
png(file="plot1.png")
x <- as.numeric(as.character(edata$Global_active_power))
hist(x,col="red",main="Globe Active Power",xlab = "Globe Active Power (kilowatts)")
dev.off()
